/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

/**
 *
 * @author na
 */
public class CreateEmployee extends javax.swing.JFrame {

    /**
     * Creates new form CreateCustomer
     */
    public CreateEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        zipCodeTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        confirmPasswordTextField = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        firstNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstNameTextField.setBorder(null);
        getContentPane().add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 200, 300, -1));

        lastNameTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        lastNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastNameTextField.setBorder(null);
        getContentPane().add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 240, 300, -1));

        addressTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        addressTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addressTextField.setBorder(null);
        getContentPane().add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 440, 440, -1));

        cityTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        cityTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cityTextField.setBorder(null);
        getContentPane().add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 280, 300, -1));

        stateTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        stateTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stateTextField.setBorder(null);
        getContentPane().add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 320, 300, -1));

        zipCodeTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        zipCodeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        zipCodeTextField.setBorder(null);
        zipCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(zipCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 360, 300, -1));

        phoneNumberTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        phoneNumberTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phoneNumberTextField.setBorder(null);
        getContentPane().add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 400, 300, -1));

        usernameTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTextField.setBorder(null);
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 80, 300, -1));

        passwordTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        passwordTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTextField.setBorder(null);
        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 120, 300, -1));

        confirmPasswordTextField.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        confirmPasswordTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPasswordTextField.setBorder(null);
        getContentPane().add(confirmPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 160, 300, -1));

        Create.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        getContentPane().add(Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 190, 40));
        Create.getAccessibleContext().setAccessibleName("");

        Cancel.setFont(new java.awt.Font("援대┝", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 190, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/CreateEmployeeBackground.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void zipCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeTextFieldActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Create;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField confirmPasswordTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
